version: "3"
services:
  phpserver:
    image: php7.4_xdebug:latest
    restart: "no"
    build:
        context: .
        dockerfile: ./images/php_7.4/Dockerfile
        args:
          - WITH_XDEBUG=true
    volumes:
      - ../project:/var/www/html
      - ./volumenes/apache/sites-enabled:/etc/apache2/sites-enabled
    ports:
      - ${HTTP_SERVER_PORT}:80
    environment:
        XDEBUG_CONFIG: remote_host=docker-host remote_port=9000
