version: "3"
services:
  phpserver:
    image: php7.4_xdebug:latest
    restart: "no"
    build:
        context: ./images/php
        dockerfile: Dockerfile
        args:
          - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ../project:/var/www/html
      - ./volumenes/apache/sites-enabled:/etc/apache2/sites-enabled
    ports:
      - ${HTTP_SERVER_PORT}:80

